apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-edge
  labels:
    app.kubernetes.io/name: erp-edge
    app.kubernetes.io/part-of: erp-platform
    app.kubernetes.io/component: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: erp-edge
  template:
    metadata:
      labels:
        app.kubernetes.io/name: erp-edge
        app.kubernetes.io/part-of: erp-platform
        erp.io/public-entrypoint: "true"
    spec:
      serviceAccountName: erp-workload
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: edge
          image: ghcr.io/thiagodifaria/erp-edge:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: erp-runtime-config
            - secretRef:
                name: erp-runtime-secrets
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            periodSeconds: 20
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 512Mi
