apiVersion: v1
kind: Namespace
metadata:
  name: erp
  labels:
    app.kubernetes.io/name: erp
    app.kubernetes.io/part-of: erp-platform
    erp.io/runtime: production
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
