apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: erp-default-deny
  labels:
    app.kubernetes.io/name: erp
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: erp-allow-ingress-to-edge
  labels:
    app.kubernetes.io/name: erp-edge
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: erp-edge
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: erp-allow-platform-internal-http
  labels:
    app.kubernetes.io/name: erp
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: erp-platform
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: erp-platform
      ports:
        - protocol: TCP
          port: 8000
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: erp-platform
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
