global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - service-prometheus:9090

  - job_name: blackbox-http
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://edge:8080/health/ready
          - http://identity:8080/health/ready
          - http://webhook-hub:8082/health/ready
          - http://service-keycloak:8080/realms/erp-local
          - http://service-openfga:8080/healthz
          - http://service-grafana:3000/api/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: service-blackbox-exporter:9115

  - job_name: blackbox-tcp
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
          - service-postgresql:5432
          - service-redis:6379
          - service-kafka:9092
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: service-blackbox-exporter:9115
